### ISSUE TITLE
shorter problem code

### ISSUE THREAD

**Issue by heavenly** [dfyz/rust-segfault#1]
Hello, I have shortened the code and resulted in the same problem, check this out:
https://pastebin.run/CHGbn5h-kX

Easier to read

**Comment by dfyz** [comment]
Hi, thank you for your help!

I might be missing something, but it doesn't seem like the same problem to me: your code panics cleanly (`thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 16777216'`). This is the expected (and perfectly valid) behaviour. To demonstrate the problem, the code should segfault (i.e., [this code](https://pastebin.run/r-Sf4Gzkzx) prints `code: line 26:     8 Segmentation fault      (core dumped)`).
