### ISSUE TITLE
Repro using the playground stable (release, 2018, 1.41.0) on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by skull-squadron** [dfyz/rust-segfault#2]
I saw the post on Reddit and thought I'd try this out.

[Playground here](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=0f3f53ab885acd9c26e3d5f4f29b6a5a) 

EDIT: updated to eliminate cargo/rustc by calling the target binary directly

**Verdict:** yep, it's hooped.

**Comment by skull-squadron** [comment]
Looks like the next step is for someone to fix a983e05 and add a test case. (I actually don't have a computer right now... Lenovo T-series decided to roll on it's back, legs crossed.)

**Comment by dfyz** [comment]
Whoa, nice playground trick! I had no idea they let you spawn binaries.

Regarding the fix: it turned out sneakier than anyone expected -- it looks like it's an LLVM bug after all. I updated the repo description with the link to the GitHub issue upstream where it's currently being investigated.

**Comment by skull-squadron** [comment]
I figured as much being how inconsistent it was.

IMHO 2cents, I would like to see Rust able to emit defensive runtime assertions with a compiler flag, even in release, because defensive-coding shouldn't be dead and defense-in-depth is beyond what test coverage can ever hope to accomplish. Invariants and pre-/post-conditions need to be double-checkable somehow in quality code (at the minor cost of increasing LoC). And, in the future, I'd like to see formal verification and property testing/fuzzing.

PS: Hehe :) Most "try online" platforms usually patch their runtimes to prevent local & remote D/DoS and PrivEsc. And if you can write files, PrivEsc and execute, you just capped the flag.
